<?php 
require_once __DIR__."/vendor/autoload.php";
require_once __DIR__. '/src/config/boostrap.php';

use App\Migrations\Usuarios;
use App\Migrations\tarefaMigration;
use App\Migrations\tabelaTarefaMigration;
use App\Migrations\Projeto;
use App\Migrations\MigrationEquipeTarefa;
use App\Migrations\MigrationEquipeProjeto;

$usuarioMigration = new Usuarios();
$usuarioMigration->up();
sleep(1);
echo '/' ;
sleep(1);
clear();
sleep(1);
echo '|' ;
sleep(1);
$projetoMigration = new Projeto();
$projetoMigration->up();
sleep(1);
echo '/' ;
sleep(1);
clear();
sleep(1);
echo '|' ;
sleep(1);
$MigrationEquipeProjeto = new MigrationEquipeProjeto();
$MigrationEquipeProjeto->up();
sleep(1);
echo '/' ;
sleep(1);
clear();
sleep(1);
echo '|' ;
sleep(1);
$MigrationEquipeTarefa = new MigrationEquipeTarefa();
$MigrationEquipeTarefa->up();
sleep(1);
echo '/' ;
sleep(1);
clear();
sleep(1);
echo '|' ;
sleep(1);
$tabelaTarefaMigration = new tabelaTarefaMigration();
$tabelaTarefaMigration->up();
sleep(1);
echo '/' ;
sleep(1);
clear();
sleep(1);
echo '|' ;
sleep(1);
$tarefaMigration = new tarefaMigration();
$tarefaMigration->up();
sleep(1);
echo '/' ;
sleep(1);
clear();
sleep(1);
echo '|' ;
sleep(1);